#
# Copyright (c) 2022  Amazon.com, Inc. or its affiliates.  All rights reserved.
#
# PROPRIETARY/CONFIDENTIAL.  USE IS SUBJECT TO LICENSE TERMS.
#

address=/dss-na.amazon.com/192.168.49.1
address=/dss-eu.amazon.com/192.168.49.1
address=/dss-jp.amazon.com/192.168.49.1
address=/dp-sps-na.amazon.com/192.168.49.1
address=/dp-sps-eu.amazon.com/192.168.49.1
address=/dp-sps-jp.amazon.com/192.168.49.1
